services:
  terriamapfe:
    build: .
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      #- ./wwwroot:/app/wwwroot
      - ./wwwroot/config.json:/app/wwwroot/config.json
      - ./wwwroot/init/simple.json:/app/wwwroot/init/simple.json
      - ./wwwroot/images:/app/wwwroot/images
      - ./serverconfig.json:/app/serverconfig.json
      #- ./node_modules:/usr/src/app/node_modules
      #- ./productionserverconfig.json:/usr/src/app/productionserverconfig.json
      #command: ["node", "./node_modules/terriajs-server/terriajs-server.js", "--config-file", "productionserverconfig.json"]
volumes:
  terriamap: {}
